//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTaskScheduler.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeTaskScheduler.Application.Resources.CommentResources", typeof(CommentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment does not exists by provided Id.
        /// </summary>
        internal static string CommentDoesNotExist {
            get {
                return ResourceManager.GetString("CommentDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Id is required.
        /// </summary>
        internal static string CommentIdIsRequired {
            get {
                return ResourceManager.GetString("CommentIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        internal static string CommentIsRequired {
            get {
                return ResourceManager.GetString("CommentIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment must be less than 2000 characters. You entered {0} characters.
        /// </summary>
        internal static string CommentPayloadLengthLimit2000 {
            get {
                return ResourceManager.GetString("CommentPayloadLengthLimit2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Target Type is required.
        /// </summary>
        internal static string CommentTargeTypeIsRequired {
            get {
                return ResourceManager.GetString("CommentTargeTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Target Type is invalid.
        /// </summary>
        internal static string InvalidCommentTargetType {
            get {
                return ResourceManager.GetString("InvalidCommentTargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no such course by provided target id.
        /// </summary>
        internal static string NoCourseByTargetId {
            get {
                return ResourceManager.GetString("NoCourseByTargetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no such task by provided target id.
        /// </summary>
        internal static string NoTaskByTargetId {
            get {
                return ResourceManager.GetString("NoTaskByTargetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Id is required.
        /// </summary>
        internal static string TargetIdIsRequired {
            get {
                return ResourceManager.GetString("TargetIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id is required.
        /// </summary>
        internal static string UserIdIsRequired {
            get {
                return ResourceManager.GetString("UserIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exists by provided Id.
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
    }
}
