//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTaskScheduler.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubmissionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmissionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeTaskScheduler.Application.Resources.SubmissionResources", typeof(SubmissionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide answer please.
        /// </summary>
        internal static string AnswerCanNotBeEmpty {
            get {
                return ResourceManager.GetString("AnswerCanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade must be between 1 and 100..
        /// </summary>
        internal static string GradeBetween1And100 {
            get {
                return ResourceManager.GetString("GradeBetween1And100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index of answer. Question : {0}.
        /// </summary>
        internal static string InvalidAnswerIndex {
            get {
                return ResourceManager.GetString("InvalidAnswerIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid index of question. Questions length: {0}, bad index: {0}.
        /// </summary>
        internal static string InvalidQuestionIndex {
            get {
                return ResourceManager.GetString("InvalidQuestionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid submission status..
        /// </summary>
        internal static string InvalidSubmissionStatus {
            get {
                return ResourceManager.GetString("InvalidSubmissionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid submission type..
        /// </summary>
        internal static string InvalidSubmissionType {
            get {
                return ResourceManager.GetString("InvalidSubmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student does not exists by provided Id.
        /// </summary>
        internal static string StudentDoestNotFound {
            get {
                return ResourceManager.GetString("StudentDoestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Id is required..
        /// </summary>
        internal static string StudentIDIsRequired {
            get {
                return ResourceManager.GetString("StudentIDIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Id is required.
        /// </summary>
        internal static string SubmissionIdIsRequired {
            get {
                return ResourceManager.GetString("SubmissionIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission does not exists by provided Id.
        /// </summary>
        internal static string SubmissionNotFound {
            get {
                return ResourceManager.GetString("SubmissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Task Configuration ID..
        /// </summary>
        internal static string TaskIdIsRequired {
            get {
                return ResourceManager.GetString("TaskIdIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task was not found bt provided id.
        /// </summary>
        internal static string TaskNotFound {
            get {
                return ResourceManager.GetString("TaskNotFound", resourceCulture);
            }
        }
    }
}
